// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiA4hqW9T4NDif-8Utf7vwLylS5lHL02Y',
    appId: '1:391708399034:web:325086349f87a791af3983',
    messagingSenderId: '391708399034',
    projectId: 'mahiecommerce',
    authDomain: 'mahiecommerce.firebaseapp.com',
    storageBucket: 'mahiecommerce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh_26XOgFJX8QPCS03DKmoR52vCSCnR0o',
    appId: '1:391708399034:android:f1cd20da59f57cbbaf3983',
    messagingSenderId: '391708399034',
    projectId: 'mahiecommerce',
    storageBucket: 'mahiecommerce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOBvBect4NZTIKDaKEL6m7m15kuR-rrJI',
    appId: '1:391708399034:ios:8f859aa76b040527af3983',
    messagingSenderId: '391708399034',
    projectId: 'mahiecommerce',
    storageBucket: 'mahiecommerce.firebasestorage.app',
    iosBundleId: 'com.ecommerce.ecommercelocal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiA4hqW9T4NDif-8Utf7vwLylS5lHL02Y',
    appId: '1:391708399034:web:d66f753421132f62af3983',
    messagingSenderId: '391708399034',
    projectId: 'mahiecommerce',
    authDomain: 'mahiecommerce.firebaseapp.com',
    storageBucket: 'mahiecommerce.firebasestorage.app',
  );
}
